/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from 'ethers'
import { Provider } from 'ethers/providers'

import { ArbBls } from './ArbBls'

export class ArbBlsFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): ArbBls {
    return new Contract(address, _abi, signerOrProvider) as ArbBls
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: 'address',
        name: 'addr',
        type: 'address',
      },
    ],
    name: 'getPublicKey',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'uint256',
        name: 'x0',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'x1',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'y0',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'y1',
        type: 'uint256',
      },
    ],
    name: 'register',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
