// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export interface SendTransactionArgs {
  maxGas?: string
  gasPriceBid?: string
  sequenceNum?: string
  destAddress?: string
  payment?: string
  data?: string
  signature?: string
}

export interface SendTransactionReply {
  accepted?: boolean
}

export interface TxAggregatorService {
  SendTransaction: (r: SendTransactionArgs) => SendTransactionReply
}
