// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace validatorserver {
  export interface TopicGroup {
    topics?: Array<string>
  }

  export interface FindLogsArgs {
    fromHeight?: string
    toHeight?: string
    addresses?: Array<string>
    topicGroups?: Array<TopicGroup>
  }

  export interface FindLogsReply {
    logs?: Array<evm.FullLogBuf>
  }

  export interface GetOutputMessageArgs {
    AssertionNodeHash?: string
    MsgIndex?: string
  }

  export interface GetOutputMessageReply {
    found?: boolean
    rawVal?: string
  }

  export interface GetMessageResultArgs {
    txHash?: string
  }

  export interface GetMessageResultReply {
    tx?: evm.TxInfoBuf
  }

  export interface GetAssertionCountArgs {}

  export interface GetAssertionCountReply {
    assertionCount?: number
  }

  export interface GetVMInfoArgs {}

  export interface GetVMInfoReply {
    vmID?: string
  }

  export interface CallMessageArgs {
    contractAddress?: string
    sender?: string
    data?: string
  }

  export interface CallMessageReply {
    rawVal?: string
  }

  export interface RollupValidatorService {
    GetOutputMessage: (r: GetOutputMessageArgs) => GetOutputMessageReply
    GetMessageResult: (r: GetMessageResultArgs) => GetMessageResultReply
    CallMessage: (r: CallMessageArgs) => CallMessageReply
    FindLogs: (r: FindLogsArgs) => FindLogsReply
    GetAssertionCount: (r: GetAssertionCountArgs) => GetAssertionCountReply
    GetVMInfo: (r: GetVMInfoArgs) => GetVMInfoReply
  }
}
