/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import { Provider } from '@ethersproject/providers'
import type { OldRollup, OldRollupInterface } from '../OldRollup'

const _abi = [
  {
    inputs: [],
    name: 'sequencerInboxMaxDelayBlocks',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'sequencerInboxMaxDelaySeconds',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

export class OldRollup__factory {
  static readonly abi = _abi
  static createInterface(): OldRollupInterface {
    return new utils.Interface(_abi) as OldRollupInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OldRollup {
    return new Contract(address, _abi, signerOrProvider) as OldRollup
  }
}
