/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import { Contract, ContractFactory, Overrides } from '@ethersproject/contracts'

import type { TesterERC20TokenNoMetadata } from '../TesterERC20TokenNoMetadata'

export class TesterERC20TokenNoMetadata__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer)
  }

  deploy(overrides?: Overrides): Promise<TesterERC20TokenNoMetadata> {
    return super.deploy(overrides || {}) as Promise<TesterERC20TokenNoMetadata>
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): TesterERC20TokenNoMetadata {
    return super.attach(address) as TesterERC20TokenNoMetadata
  }
  connect(signer: Signer): TesterERC20TokenNoMetadata__factory {
    return super.connect(signer) as TesterERC20TokenNoMetadata__factory
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TesterERC20TokenNoMetadata {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TesterERC20TokenNoMetadata
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
]

const _bytecode =
  '0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212209997ccdb3e94e790e4d6cdaaa8c5e09441c6be420deab63e592e540ce69254ca64736f6c634300060b0033'
