//
// Copyright 2019-2020, Offchain Labs, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: evm.proto

package evm

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NodeLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeHash   string `protobuf:"bytes,1,opt,name=nodeHash,proto3" json:"nodeHash,omitempty"`
	NodeHeight uint64 `protobuf:"varint,2,opt,name=nodeHeight,proto3" json:"nodeHeight,omitempty"`
	L1TxHash   string `protobuf:"bytes,3,opt,name=l1TxHash,proto3" json:"l1TxHash,omitempty"`
}

func (x *NodeLocation) Reset() {
	*x = NodeLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLocation) ProtoMessage() {}

func (x *NodeLocation) ProtoReflect() protoreflect.Message {
	mi := &file_evm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLocation.ProtoReflect.Descriptor instead.
func (*NodeLocation) Descriptor() ([]byte, []int) {
	return file_evm_proto_rawDescGZIP(), []int{0}
}

func (x *NodeLocation) GetNodeHash() string {
	if x != nil {
		return x.NodeHash
	}
	return ""
}

func (x *NodeLocation) GetNodeHeight() uint64 {
	if x != nil {
		return x.NodeHeight
	}
	return 0
}

func (x *NodeLocation) GetL1TxHash() string {
	if x != nil {
		return x.L1TxHash
	}
	return ""
}

type FullLogBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address          string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Location         *NodeLocation `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Data             string        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	LogIndex         string        `protobuf:"bytes,5,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	Topics           []string      `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty"`
	TransactionIndex string        `protobuf:"bytes,7,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	TransactionHash  string        `protobuf:"bytes,8,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Index            string        `protobuf:"bytes,9,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *FullLogBuf) Reset() {
	*x = FullLogBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullLogBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullLogBuf) ProtoMessage() {}

func (x *FullLogBuf) ProtoReflect() protoreflect.Message {
	mi := &file_evm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullLogBuf.ProtoReflect.Descriptor instead.
func (*FullLogBuf) Descriptor() ([]byte, []int) {
	return file_evm_proto_rawDescGZIP(), []int{1}
}

func (x *FullLogBuf) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FullLogBuf) GetLocation() *NodeLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FullLogBuf) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *FullLogBuf) GetLogIndex() string {
	if x != nil {
		return x.LogIndex
	}
	return ""
}

func (x *FullLogBuf) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *FullLogBuf) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *FullLogBuf) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *FullLogBuf) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

type AVMLogProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogPreHash   string   `protobuf:"bytes,1,opt,name=logPreHash,proto3" json:"logPreHash,omitempty"`
	LogPostHash  string   `protobuf:"bytes,2,opt,name=logPostHash,proto3" json:"logPostHash,omitempty"`
	LogValHashes []string `protobuf:"bytes,3,rep,name=logValHashes,proto3" json:"logValHashes,omitempty"`
}

func (x *AVMLogProof) Reset() {
	*x = AVMLogProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AVMLogProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AVMLogProof) ProtoMessage() {}

func (x *AVMLogProof) ProtoReflect() protoreflect.Message {
	mi := &file_evm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AVMLogProof.ProtoReflect.Descriptor instead.
func (*AVMLogProof) Descriptor() ([]byte, []int) {
	return file_evm_proto_rawDescGZIP(), []int{2}
}

func (x *AVMLogProof) GetLogPreHash() string {
	if x != nil {
		return x.LogPreHash
	}
	return ""
}

func (x *AVMLogProof) GetLogPostHash() string {
	if x != nil {
		return x.LogPostHash
	}
	return ""
}

func (x *AVMLogProof) GetLogValHashes() []string {
	if x != nil {
		return x.LogValHashes
	}
	return nil
}

type TxInfoBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found         bool          `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	RawVal        string        `protobuf:"bytes,2,opt,name=rawVal,proto3" json:"rawVal,omitempty"`
	TxHash        string        `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
	TxIndex       uint64        `protobuf:"varint,4,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	StartLogIndex uint64        `protobuf:"varint,5,opt,name=startLogIndex,proto3" json:"startLogIndex,omitempty"`
	Location      *NodeLocation `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Proof         *AVMLogProof  `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *TxInfoBuf) Reset() {
	*x = TxInfoBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxInfoBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInfoBuf) ProtoMessage() {}

func (x *TxInfoBuf) ProtoReflect() protoreflect.Message {
	mi := &file_evm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInfoBuf.ProtoReflect.Descriptor instead.
func (*TxInfoBuf) Descriptor() ([]byte, []int) {
	return file_evm_proto_rawDescGZIP(), []int{3}
}

func (x *TxInfoBuf) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TxInfoBuf) GetRawVal() string {
	if x != nil {
		return x.RawVal
	}
	return ""
}

func (x *TxInfoBuf) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxInfoBuf) GetTxIndex() uint64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *TxInfoBuf) GetStartLogIndex() uint64 {
	if x != nil {
		return x.StartLogIndex
	}
	return 0
}

func (x *TxInfoBuf) GetLocation() *NodeLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TxInfoBuf) GetProof() *AVMLogProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_evm_proto protoreflect.FileDescriptor

var file_evm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x76, 0x6d,
	0x22, 0x66, 0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a,
	0x6e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x31, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x31, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x89, 0x02, 0x0a, 0x0a, 0x46, 0x75, 0x6c,
	0x6c, 0x4c, 0x6f, 0x67, 0x42, 0x75, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x2d, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x76, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x73, 0x0a, 0x0b, 0x41, 0x56, 0x4d, 0x4c, 0x6f, 0x67, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x50, 0x72, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x50, 0x72, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x56, 0x61, 0x6c, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x67,
	0x56, 0x61, 0x6c, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0xe8, 0x01, 0x0a, 0x09, 0x54, 0x78,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x75, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x77, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x61, 0x77, 0x56, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2d, 0x0a,
	0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x65, 0x76, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x05,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x76,
	0x6d, 0x2e, 0x41, 0x56, 0x4d, 0x4c, 0x6f, 0x67, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6c, 0x61, 0x62, 0x73, 0x2f,
	0x61, 0x72, 0x62, 0x69, 0x74, 0x72, 0x75, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x61, 0x72, 0x62, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2d,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x76, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_evm_proto_rawDescOnce sync.Once
	file_evm_proto_rawDescData = file_evm_proto_rawDesc
)

func file_evm_proto_rawDescGZIP() []byte {
	file_evm_proto_rawDescOnce.Do(func() {
		file_evm_proto_rawDescData = protoimpl.X.CompressGZIP(file_evm_proto_rawDescData)
	})
	return file_evm_proto_rawDescData
}

var file_evm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_evm_proto_goTypes = []interface{}{
	(*NodeLocation)(nil), // 0: evm.NodeLocation
	(*FullLogBuf)(nil),   // 1: evm.FullLogBuf
	(*AVMLogProof)(nil),  // 2: evm.AVMLogProof
	(*TxInfoBuf)(nil),    // 3: evm.TxInfoBuf
}
var file_evm_proto_depIdxs = []int32{
	0, // 0: evm.FullLogBuf.location:type_name -> evm.NodeLocation
	0, // 1: evm.TxInfoBuf.location:type_name -> evm.NodeLocation
	2, // 2: evm.TxInfoBuf.proof:type_name -> evm.AVMLogProof
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_evm_proto_init() }
func file_evm_proto_init() {
	if File_evm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_evm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullLogBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AVMLogProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxInfoBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_evm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evm_proto_goTypes,
		DependencyIndexes: file_evm_proto_depIdxs,
		MessageInfos:      file_evm_proto_msgTypes,
	}.Build()
	File_evm_proto = out.File
	file_evm_proto_rawDesc = nil
	file_evm_proto_goTypes = nil
	file_evm_proto_depIdxs = nil
}
