// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rollup.proto

package rollup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	value "github.com/offchainlabs/arbitrum/packages/arb-util/value"
	structures "github.com/offchainlabs/arbitrum/packages/arb-validator/structures"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeBuf struct {
	PrevHash             *value.HashBuf                `protobuf:"bytes,1,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Deadline             *structures.TimeTicksBuf      `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DisputableNode       *structures.DisputableNodeBuf `protobuf:"bytes,3,opt,name=disputableNode,proto3" json:"disputableNode,omitempty"`
	LinkType             uint32                        `protobuf:"varint,4,opt,name=linkType,proto3" json:"linkType,omitempty"`
	VmProtoData          *structures.VMProtoDataBuf    `protobuf:"bytes,5,opt,name=vmProtoData,proto3" json:"vmProtoData,omitempty"`
	MachineHash          *value.HashBuf                `protobuf:"bytes,6,opt,name=machineHash,proto3" json:"machineHash,omitempty"`
	Depth                uint64                        `protobuf:"varint,7,opt,name=depth,proto3" json:"depth,omitempty"`
	InnerHash            *value.HashBuf                `protobuf:"bytes,8,opt,name=innerHash,proto3" json:"innerHash,omitempty"`
	Hash                 *value.HashBuf                `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NodeBuf) Reset()         { *m = NodeBuf{} }
func (m *NodeBuf) String() string { return proto.CompactTextString(m) }
func (*NodeBuf) ProtoMessage()    {}
func (*NodeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{0}
}

func (m *NodeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeBuf.Unmarshal(m, b)
}
func (m *NodeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeBuf.Marshal(b, m, deterministic)
}
func (m *NodeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeBuf.Merge(m, src)
}
func (m *NodeBuf) XXX_Size() int {
	return xxx_messageInfo_NodeBuf.Size(m)
}
func (m *NodeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_NodeBuf proto.InternalMessageInfo

func (m *NodeBuf) GetPrevHash() *value.HashBuf {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *NodeBuf) GetDeadline() *structures.TimeTicksBuf {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *NodeBuf) GetDisputableNode() *structures.DisputableNodeBuf {
	if m != nil {
		return m.DisputableNode
	}
	return nil
}

func (m *NodeBuf) GetLinkType() uint32 {
	if m != nil {
		return m.LinkType
	}
	return 0
}

func (m *NodeBuf) GetVmProtoData() *structures.VMProtoDataBuf {
	if m != nil {
		return m.VmProtoData
	}
	return nil
}

func (m *NodeBuf) GetMachineHash() *value.HashBuf {
	if m != nil {
		return m.MachineHash
	}
	return nil
}

func (m *NodeBuf) GetDepth() uint64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *NodeBuf) GetInnerHash() *value.HashBuf {
	if m != nil {
		return m.InnerHash
	}
	return nil
}

func (m *NodeBuf) GetHash() *value.HashBuf {
	if m != nil {
		return m.Hash
	}
	return nil
}

type NodeGraphBuf struct {
	Nodes                []*NodeBuf                 `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	OldestNodeHash       *value.HashBuf             `protobuf:"bytes,2,opt,name=oldestNodeHash,proto3" json:"oldestNodeHash,omitempty"`
	LatestConfirmedHash  *value.HashBuf             `protobuf:"bytes,3,opt,name=latestConfirmedHash,proto3" json:"latestConfirmedHash,omitempty"`
	LeafHashes           []*value.HashBuf           `protobuf:"bytes,4,rep,name=leafHashes,proto3" json:"leafHashes,omitempty"`
	Params               *structures.ChainParamsBuf `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NodeGraphBuf) Reset()         { *m = NodeGraphBuf{} }
func (m *NodeGraphBuf) String() string { return proto.CompactTextString(m) }
func (*NodeGraphBuf) ProtoMessage()    {}
func (*NodeGraphBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{1}
}

func (m *NodeGraphBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGraphBuf.Unmarshal(m, b)
}
func (m *NodeGraphBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGraphBuf.Marshal(b, m, deterministic)
}
func (m *NodeGraphBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGraphBuf.Merge(m, src)
}
func (m *NodeGraphBuf) XXX_Size() int {
	return xxx_messageInfo_NodeGraphBuf.Size(m)
}
func (m *NodeGraphBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGraphBuf.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGraphBuf proto.InternalMessageInfo

func (m *NodeGraphBuf) GetNodes() []*NodeBuf {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *NodeGraphBuf) GetOldestNodeHash() *value.HashBuf {
	if m != nil {
		return m.OldestNodeHash
	}
	return nil
}

func (m *NodeGraphBuf) GetLatestConfirmedHash() *value.HashBuf {
	if m != nil {
		return m.LatestConfirmedHash
	}
	return nil
}

func (m *NodeGraphBuf) GetLeafHashes() []*value.HashBuf {
	if m != nil {
		return m.LeafHashes
	}
	return nil
}

func (m *NodeGraphBuf) GetParams() *structures.ChainParamsBuf {
	if m != nil {
		return m.Params
	}
	return nil
}

type StakedNodeGraphBuf struct {
	NodeGraph            *NodeGraphBuf   `protobuf:"bytes,1,opt,name=nodeGraph,proto3" json:"nodeGraph,omitempty"`
	Stakers              []*StakerBuf    `protobuf:"bytes,2,rep,name=stakers,proto3" json:"stakers,omitempty"`
	Challenges           []*ChallengeBuf `protobuf:"bytes,3,rep,name=challenges,proto3" json:"challenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StakedNodeGraphBuf) Reset()         { *m = StakedNodeGraphBuf{} }
func (m *StakedNodeGraphBuf) String() string { return proto.CompactTextString(m) }
func (*StakedNodeGraphBuf) ProtoMessage()    {}
func (*StakedNodeGraphBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{2}
}

func (m *StakedNodeGraphBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakedNodeGraphBuf.Unmarshal(m, b)
}
func (m *StakedNodeGraphBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakedNodeGraphBuf.Marshal(b, m, deterministic)
}
func (m *StakedNodeGraphBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakedNodeGraphBuf.Merge(m, src)
}
func (m *StakedNodeGraphBuf) XXX_Size() int {
	return xxx_messageInfo_StakedNodeGraphBuf.Size(m)
}
func (m *StakedNodeGraphBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_StakedNodeGraphBuf.DiscardUnknown(m)
}

var xxx_messageInfo_StakedNodeGraphBuf proto.InternalMessageInfo

func (m *StakedNodeGraphBuf) GetNodeGraph() *NodeGraphBuf {
	if m != nil {
		return m.NodeGraph
	}
	return nil
}

func (m *StakedNodeGraphBuf) GetStakers() []*StakerBuf {
	if m != nil {
		return m.Stakers
	}
	return nil
}

func (m *StakedNodeGraphBuf) GetChallenges() []*ChallengeBuf {
	if m != nil {
		return m.Challenges
	}
	return nil
}

type ChainObserverBuf struct {
	StakedNodeGraph      *StakedNodeGraphBuf `protobuf:"bytes,1,opt,name=stakedNodeGraph,proto3" json:"stakedNodeGraph,omitempty"`
	ContractAddress      []byte              `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	PendingInbox         *PendingInboxBuf    `protobuf:"bytes,3,opt,name=pendingInbox,proto3" json:"pendingInbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChainObserverBuf) Reset()         { *m = ChainObserverBuf{} }
func (m *ChainObserverBuf) String() string { return proto.CompactTextString(m) }
func (*ChainObserverBuf) ProtoMessage()    {}
func (*ChainObserverBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{3}
}

func (m *ChainObserverBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainObserverBuf.Unmarshal(m, b)
}
func (m *ChainObserverBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainObserverBuf.Marshal(b, m, deterministic)
}
func (m *ChainObserverBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainObserverBuf.Merge(m, src)
}
func (m *ChainObserverBuf) XXX_Size() int {
	return xxx_messageInfo_ChainObserverBuf.Size(m)
}
func (m *ChainObserverBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainObserverBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ChainObserverBuf proto.InternalMessageInfo

func (m *ChainObserverBuf) GetStakedNodeGraph() *StakedNodeGraphBuf {
	if m != nil {
		return m.StakedNodeGraph
	}
	return nil
}

func (m *ChainObserverBuf) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *ChainObserverBuf) GetPendingInbox() *PendingInboxBuf {
	if m != nil {
		return m.PendingInbox
	}
	return nil
}

type StakerBuf struct {
	Address              []byte                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Location             *value.HashBuf           `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	CreationTime         *structures.TimeTicksBuf `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	ChallengeAddr        []byte                   `protobuf:"bytes,4,opt,name=challengeAddr,proto3" json:"challengeAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StakerBuf) Reset()         { *m = StakerBuf{} }
func (m *StakerBuf) String() string { return proto.CompactTextString(m) }
func (*StakerBuf) ProtoMessage()    {}
func (*StakerBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{4}
}

func (m *StakerBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakerBuf.Unmarshal(m, b)
}
func (m *StakerBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakerBuf.Marshal(b, m, deterministic)
}
func (m *StakerBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakerBuf.Merge(m, src)
}
func (m *StakerBuf) XXX_Size() int {
	return xxx_messageInfo_StakerBuf.Size(m)
}
func (m *StakerBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_StakerBuf.DiscardUnknown(m)
}

var xxx_messageInfo_StakerBuf proto.InternalMessageInfo

func (m *StakerBuf) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *StakerBuf) GetLocation() *value.HashBuf {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *StakerBuf) GetCreationTime() *structures.TimeTicksBuf {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *StakerBuf) GetChallengeAddr() []byte {
	if m != nil {
		return m.ChallengeAddr
	}
	return nil
}

type ChallengeBuf struct {
	Contract             []byte   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Asserter             []byte   `protobuf:"bytes,2,opt,name=asserter,proto3" json:"asserter,omitempty"`
	Challenger           []byte   `protobuf:"bytes,3,opt,name=challenger,proto3" json:"challenger,omitempty"`
	Kind                 uint32   `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChallengeBuf) Reset()         { *m = ChallengeBuf{} }
func (m *ChallengeBuf) String() string { return proto.CompactTextString(m) }
func (*ChallengeBuf) ProtoMessage()    {}
func (*ChallengeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{5}
}

func (m *ChallengeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChallengeBuf.Unmarshal(m, b)
}
func (m *ChallengeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChallengeBuf.Marshal(b, m, deterministic)
}
func (m *ChallengeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeBuf.Merge(m, src)
}
func (m *ChallengeBuf) XXX_Size() int {
	return xxx_messageInfo_ChallengeBuf.Size(m)
}
func (m *ChallengeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeBuf proto.InternalMessageInfo

func (m *ChallengeBuf) GetContract() []byte {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *ChallengeBuf) GetAsserter() []byte {
	if m != nil {
		return m.Asserter
	}
	return nil
}

func (m *ChallengeBuf) GetChallenger() []byte {
	if m != nil {
		return m.Challenger
	}
	return nil
}

func (m *ChallengeBuf) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

type PendingInboxBuf struct {
	Items                [][]byte       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HashOfRest           *value.HashBuf `protobuf:"bytes,2,opt,name=hashOfRest,proto3" json:"hashOfRest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PendingInboxBuf) Reset()         { *m = PendingInboxBuf{} }
func (m *PendingInboxBuf) String() string { return proto.CompactTextString(m) }
func (*PendingInboxBuf) ProtoMessage()    {}
func (*PendingInboxBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{6}
}

func (m *PendingInboxBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingInboxBuf.Unmarshal(m, b)
}
func (m *PendingInboxBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingInboxBuf.Marshal(b, m, deterministic)
}
func (m *PendingInboxBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingInboxBuf.Merge(m, src)
}
func (m *PendingInboxBuf) XXX_Size() int {
	return xxx_messageInfo_PendingInboxBuf.Size(m)
}
func (m *PendingInboxBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingInboxBuf.DiscardUnknown(m)
}

var xxx_messageInfo_PendingInboxBuf proto.InternalMessageInfo

func (m *PendingInboxBuf) GetItems() [][]byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PendingInboxBuf) GetHashOfRest() *value.HashBuf {
	if m != nil {
		return m.HashOfRest
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeBuf)(nil), "rollup.NodeBuf")
	proto.RegisterType((*NodeGraphBuf)(nil), "rollup.NodeGraphBuf")
	proto.RegisterType((*StakedNodeGraphBuf)(nil), "rollup.StakedNodeGraphBuf")
	proto.RegisterType((*ChainObserverBuf)(nil), "rollup.ChainObserverBuf")
	proto.RegisterType((*StakerBuf)(nil), "rollup.StakerBuf")
	proto.RegisterType((*ChallengeBuf)(nil), "rollup.ChallengeBuf")
	proto.RegisterType((*PendingInboxBuf)(nil), "rollup.PendingInboxBuf")
}

func init() { proto.RegisterFile("rollup.proto", fileDescriptor_037f188b50610c79) }

var fileDescriptor_037f188b50610c79 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0x96, 0x93, 0x34, 0x8f, 0x13, 0xb7, 0xb9, 0x9d, 0x5b, 0xe9, 0x5a, 0xb9, 0xba, 0x57, 0x91,
	0x05, 0x52, 0xc4, 0x23, 0x41, 0xa1, 0x62, 0x43, 0x85, 0x4a, 0x5b, 0x04, 0x2c, 0xa0, 0x95, 0xa9,
	0x40, 0x62, 0x37, 0xb1, 0x4f, 0x92, 0x51, 0xec, 0xb1, 0x35, 0x33, 0x8e, 0x80, 0xbf, 0xc1, 0x7f,
	0x60, 0xc3, 0x9a, 0x35, 0x7f, 0x0d, 0xcd, 0xf8, 0x11, 0x3b, 0x4a, 0x37, 0xd1, 0x9c, 0xf9, 0xbe,
	0xf3, 0xfa, 0xce, 0xf8, 0x04, 0x6c, 0x11, 0x87, 0x61, 0x9a, 0x4c, 0x12, 0x11, 0xab, 0x98, 0xb4,
	0x33, 0x6b, 0x78, 0xbc, 0xa1, 0x61, 0x8a, 0x53, 0xf3, 0x9b, 0x41, 0xc3, 0x7f, 0xa5, 0x12, 0xa9,
	0xaf, 0x52, 0x81, 0x72, 0xba, 0x3d, 0x66, 0xa0, 0xfb, 0xa3, 0x09, 0x9d, 0xf7, 0x71, 0x80, 0x17,
	0xe9, 0x82, 0x3c, 0x80, 0x6e, 0x22, 0x70, 0xf3, 0x86, 0xca, 0x95, 0x63, 0x8d, 0xac, 0x71, 0x7f,
	0x76, 0x34, 0xc9, 0x02, 0xe9, 0xab, 0x8b, 0x74, 0xe1, 0x95, 0x38, 0x39, 0x85, 0x6e, 0x80, 0x34,
	0x08, 0x19, 0x47, 0xa7, 0x61, 0xb8, 0xce, 0xa4, 0x12, 0xfc, 0x96, 0x45, 0x78, 0xcb, 0xfc, 0xb5,
	0x34, 0x5e, 0x05, 0x93, 0xbc, 0x82, 0xa3, 0x80, 0xc9, 0x24, 0x55, 0x74, 0x1e, 0xa2, 0x4e, 0xeb,
	0x34, 0x8d, 0xef, 0x7f, 0x55, 0xdf, 0xab, 0x1a, 0x43, 0x07, 0xd8, 0x71, 0x22, 0x43, 0xe8, 0x86,
	0x8c, 0xaf, 0x6f, 0xbf, 0x26, 0xe8, 0xb4, 0x46, 0xd6, 0xf8, 0xd0, 0x2b, 0x6d, 0x72, 0x06, 0xfd,
	0x4d, 0x74, 0xa3, 0x7b, 0xbb, 0xa2, 0x8a, 0x3a, 0x07, 0x26, 0xfe, 0xb0, 0x1a, 0xff, 0xe3, 0xbb,
	0x12, 0xd6, 0xc1, 0xab, 0x74, 0xf2, 0x04, 0xfa, 0x11, 0xf5, 0x57, 0x8c, 0xa3, 0x51, 0xa1, 0xbd,
	0x57, 0x85, 0x2a, 0x85, 0x9c, 0xc0, 0x41, 0x80, 0x89, 0x5a, 0x39, 0x9d, 0x91, 0x35, 0x6e, 0x79,
	0x99, 0x41, 0x1e, 0x41, 0x8f, 0x71, 0x8e, 0xc2, 0x44, 0xe9, 0xee, 0x8d, 0xb2, 0x25, 0x10, 0x17,
	0x5a, 0x2b, 0x4d, 0xec, 0xed, 0x25, 0x1a, 0xcc, 0xfd, 0xde, 0x00, 0x5b, 0x37, 0xff, 0x5a, 0xd0,
	0x44, 0x5f, 0x93, 0xfb, 0x70, 0xc0, 0xe3, 0x00, 0xa5, 0x63, 0x8d, 0x9a, 0xe3, 0xfe, 0x6c, 0x30,
	0xc9, 0xdf, 0x43, 0x21, 0x5a, 0x86, 0x92, 0x67, 0x70, 0x14, 0x87, 0x01, 0x4a, 0xa5, 0xef, 0x4d,
	0x39, 0x8d, 0xbd, 0x59, 0x76, 0x58, 0xe4, 0x1c, 0xfe, 0x0e, 0xa9, 0x42, 0xa9, 0x2e, 0x63, 0xbe,
	0x60, 0x22, 0xc2, 0xc0, 0x38, 0x37, 0xf7, 0x3a, 0xef, 0xa3, 0x92, 0x09, 0x40, 0x88, 0x74, 0xa1,
	0xcf, 0x28, 0x9d, 0x96, 0xa9, 0x72, 0xd7, 0xb1, 0xc2, 0x20, 0x33, 0x68, 0x27, 0x54, 0xd0, 0x48,
	0xee, 0x1b, 0xda, 0xe5, 0x8a, 0x32, 0x7e, 0x63, 0x60, 0xed, 0x97, 0x33, 0xdd, 0x9f, 0x16, 0x90,
	0x0f, 0x8a, 0xae, 0x31, 0xa8, 0x69, 0x33, 0x83, 0x1e, 0x2f, 0xec, 0xfc, 0x29, 0x9f, 0x54, 0xf5,
	0x29, 0x88, 0xde, 0x96, 0x46, 0x1e, 0x42, 0x47, 0xea, 0x48, 0x42, 0x3a, 0x0d, 0x53, 0xeb, 0x71,
	0xe1, 0x61, 0x12, 0x08, 0x4d, 0x2f, 0x18, 0xe4, 0x14, 0xc0, 0x5f, 0xd1, 0x30, 0x44, 0xbe, 0x44,
	0xe9, 0x34, 0x0d, 0xbf, 0xcc, 0x70, 0x59, 0x20, 0xa6, 0xc3, 0x2d, 0xcf, 0xfd, 0x6d, 0xc1, 0x5f,
	0xa6, 0x91, 0xeb, 0xb9, 0x44, 0xb1, 0x31, 0x31, 0xc9, 0x15, 0x0c, 0x64, 0xbd, 0x83, 0xbc, 0xe2,
	0x61, 0x2d, 0x7f, 0xad, 0x41, 0x6f, 0xd7, 0x85, 0x8c, 0x61, 0xe0, 0xc7, 0x5c, 0x09, 0xea, 0xab,
	0x97, 0x41, 0x20, 0x50, 0x4a, 0x33, 0x67, 0xdb, 0xdb, 0xbd, 0x26, 0xcf, 0xc1, 0x4e, 0x90, 0x07,
	0x8c, 0x2f, 0xdf, 0xf2, 0x79, 0xfc, 0x25, 0x9f, 0xe8, 0x3f, 0x45, 0xb2, 0x9b, 0x0a, 0xa6, 0x33,
	0xd5, 0xc8, 0xee, 0x2f, 0x0b, 0x7a, 0xa5, 0x1c, 0xc4, 0x81, 0x0e, 0xcd, 0x93, 0x59, 0x26, 0x59,
	0x61, 0xea, 0x55, 0x12, 0xc6, 0x3e, 0x55, 0x2c, 0xe6, 0x77, 0xbc, 0xb7, 0x12, 0x27, 0x67, 0x60,
	0xfb, 0x02, 0xcd, 0x59, 0xaf, 0x8d, 0xbc, 0xa0, 0xbb, 0xd7, 0x49, 0x8d, 0x4d, 0xee, 0xc1, 0x61,
	0xa9, 0xb0, 0x6e, 0xd1, 0x2c, 0x04, 0xdb, 0xab, 0x5f, 0xba, 0xdf, 0xc0, 0xae, 0x4e, 0x45, 0x6f,
	0x90, 0x42, 0x97, 0xbc, 0xf4, 0xd2, 0xd6, 0x18, 0x95, 0x12, 0x85, 0x42, 0x91, 0x6b, 0x58, 0xda,
	0xe4, 0xff, 0xca, 0xdc, 0x85, 0xa9, 0xd4, 0xae, 0x4c, 0x58, 0x10, 0x02, 0xad, 0x35, 0xe3, 0x41,
	0xbe, 0x95, 0xcc, 0xd9, 0xfd, 0x04, 0x83, 0x1d, 0x51, 0xf5, 0xd2, 0x60, 0x0a, 0xa3, 0xec, 0xdb,
	0xb5, 0xbd, 0xcc, 0xd0, 0x1f, 0x8c, 0xfe, 0xd4, 0xaf, 0x17, 0x1e, 0x4a, 0x75, 0x87, 0x6c, 0x15,
	0xc6, 0xc5, 0xf9, 0xe7, 0x17, 0x4b, 0xa6, 0x56, 0xe9, 0x7c, 0xe2, 0xc7, 0xd1, 0x34, 0x5e, 0x2c,
	0x7c, 0xfd, 0xb6, 0x42, 0x3a, 0x97, 0x53, 0x2a, 0xe6, 0x4c, 0x89, 0x34, 0x9a, 0x26, 0xd4, 0x5f,
	0xd3, 0x25, 0x9a, 0x9b, 0xc7, 0x1b, 0x1a, 0xb2, 0x80, 0xaa, 0x58, 0x4c, 0xb3, 0x61, 0xcf, 0xdb,
	0xe6, 0x4f, 0xe0, 0xe9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xcd, 0x20, 0x02, 0x4c, 0x06,
	0x00, 0x00,
}
