// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rollup.proto

package rollup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChainBuf struct {
	ContractAddress      string          `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	VmParams             *ChainParamsBuf `protobuf:"bytes,2,opt,name=vmParams,proto3" json:"vmParams,omitempty"`
	Nodes                []*NodeBuf      `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LatestConfirmedHash  string          `protobuf:"bytes,4,opt,name=latestConfirmedHash,proto3" json:"latestConfirmedHash,omitempty"`
	LeafHashes           []string        `protobuf:"bytes,5,rep,name=leafHashes,proto3" json:"leafHashes,omitempty"`
	Stakers              []*StakerBuf    `protobuf:"bytes,6,rep,name=stakers,proto3" json:"stakers,omitempty"`
	Challenges           []*ChallengeBuf `protobuf:"bytes,7,rep,name=challenges,proto3" json:"challenges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChainBuf) Reset()         { *m = ChainBuf{} }
func (m *ChainBuf) String() string { return proto.CompactTextString(m) }
func (*ChainBuf) ProtoMessage()    {}
func (*ChainBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{0}
}

func (m *ChainBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainBuf.Unmarshal(m, b)
}
func (m *ChainBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainBuf.Marshal(b, m, deterministic)
}
func (m *ChainBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainBuf.Merge(m, src)
}
func (m *ChainBuf) XXX_Size() int {
	return xxx_messageInfo_ChainBuf.Size(m)
}
func (m *ChainBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ChainBuf proto.InternalMessageInfo

func (m *ChainBuf) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ChainBuf) GetVmParams() *ChainParamsBuf {
	if m != nil {
		return m.VmParams
	}
	return nil
}

func (m *ChainBuf) GetNodes() []*NodeBuf {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ChainBuf) GetLatestConfirmedHash() string {
	if m != nil {
		return m.LatestConfirmedHash
	}
	return ""
}

func (m *ChainBuf) GetLeafHashes() []string {
	if m != nil {
		return m.LeafHashes
	}
	return nil
}

func (m *ChainBuf) GetStakers() []*StakerBuf {
	if m != nil {
		return m.Stakers
	}
	return nil
}

func (m *ChainBuf) GetChallenges() []*ChallengeBuf {
	if m != nil {
		return m.Challenges
	}
	return nil
}

type ChainParamsBuf struct {
	StakeRequirement     string           `protobuf:"bytes,1,opt,name=stakeRequirement,proto3" json:"stakeRequirement,omitempty"`
	GracePeriod          uint32           `protobuf:"varint,2,opt,name=gracePeriod,proto3" json:"gracePeriod,omitempty"`
	MaxExecutionSteps    uint32           `protobuf:"varint,3,opt,name=maxExecutionSteps,proto3" json:"maxExecutionSteps,omitempty"`
	PendingInbox         *PendingInboxBuf `protobuf:"bytes,4,opt,name=pendingInbox,proto3" json:"pendingInbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChainParamsBuf) Reset()         { *m = ChainParamsBuf{} }
func (m *ChainParamsBuf) String() string { return proto.CompactTextString(m) }
func (*ChainParamsBuf) ProtoMessage()    {}
func (*ChainParamsBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{1}
}

func (m *ChainParamsBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainParamsBuf.Unmarshal(m, b)
}
func (m *ChainParamsBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainParamsBuf.Marshal(b, m, deterministic)
}
func (m *ChainParamsBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainParamsBuf.Merge(m, src)
}
func (m *ChainParamsBuf) XXX_Size() int {
	return xxx_messageInfo_ChainParamsBuf.Size(m)
}
func (m *ChainParamsBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainParamsBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ChainParamsBuf proto.InternalMessageInfo

func (m *ChainParamsBuf) GetStakeRequirement() string {
	if m != nil {
		return m.StakeRequirement
	}
	return ""
}

func (m *ChainParamsBuf) GetGracePeriod() uint32 {
	if m != nil {
		return m.GracePeriod
	}
	return 0
}

func (m *ChainParamsBuf) GetMaxExecutionSteps() uint32 {
	if m != nil {
		return m.MaxExecutionSteps
	}
	return 0
}

func (m *ChainParamsBuf) GetPendingInbox() *PendingInboxBuf {
	if m != nil {
		return m.PendingInbox
	}
	return nil
}

type NodeBuf struct {
	Hash                 string             `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	DisputableNode       *DisputableNodeBuf `protobuf:"bytes,2,opt,name=disputableNode,proto3" json:"disputableNode,omitempty"`
	MachineHash          string             `protobuf:"bytes,3,opt,name=machineHash,proto3" json:"machineHash,omitempty"`
	LinkType             uint32             `protobuf:"varint,4,opt,name=linkType,proto3" json:"linkType,omitempty"`
	PrevHash             string             `protobuf:"bytes,5,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeBuf) Reset()         { *m = NodeBuf{} }
func (m *NodeBuf) String() string { return proto.CompactTextString(m) }
func (*NodeBuf) ProtoMessage()    {}
func (*NodeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{2}
}

func (m *NodeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeBuf.Unmarshal(m, b)
}
func (m *NodeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeBuf.Marshal(b, m, deterministic)
}
func (m *NodeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeBuf.Merge(m, src)
}
func (m *NodeBuf) XXX_Size() int {
	return xxx_messageInfo_NodeBuf.Size(m)
}
func (m *NodeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_NodeBuf proto.InternalMessageInfo

func (m *NodeBuf) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *NodeBuf) GetDisputableNode() *DisputableNodeBuf {
	if m != nil {
		return m.DisputableNode
	}
	return nil
}

func (m *NodeBuf) GetMachineHash() string {
	if m != nil {
		return m.MachineHash
	}
	return ""
}

func (m *NodeBuf) GetLinkType() uint32 {
	if m != nil {
		return m.LinkType
	}
	return 0
}

func (m *NodeBuf) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

type StakerBuf struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	CreationTime         string   `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	ChallengeAddr        string   `protobuf:"bytes,4,opt,name=challengeAddr,proto3" json:"challengeAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakerBuf) Reset()         { *m = StakerBuf{} }
func (m *StakerBuf) String() string { return proto.CompactTextString(m) }
func (*StakerBuf) ProtoMessage()    {}
func (*StakerBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{3}
}

func (m *StakerBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakerBuf.Unmarshal(m, b)
}
func (m *StakerBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakerBuf.Marshal(b, m, deterministic)
}
func (m *StakerBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakerBuf.Merge(m, src)
}
func (m *StakerBuf) XXX_Size() int {
	return xxx_messageInfo_StakerBuf.Size(m)
}
func (m *StakerBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_StakerBuf.DiscardUnknown(m)
}

var xxx_messageInfo_StakerBuf proto.InternalMessageInfo

func (m *StakerBuf) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StakerBuf) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *StakerBuf) GetCreationTime() string {
	if m != nil {
		return m.CreationTime
	}
	return ""
}

func (m *StakerBuf) GetChallengeAddr() string {
	if m != nil {
		return m.ChallengeAddr
	}
	return ""
}

type ChallengeBuf struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Asserter             string   `protobuf:"bytes,2,opt,name=asserter,proto3" json:"asserter,omitempty"`
	Challenger           string   `protobuf:"bytes,3,opt,name=challenger,proto3" json:"challenger,omitempty"`
	Kind                 uint32   `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChallengeBuf) Reset()         { *m = ChallengeBuf{} }
func (m *ChallengeBuf) String() string { return proto.CompactTextString(m) }
func (*ChallengeBuf) ProtoMessage()    {}
func (*ChallengeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{4}
}

func (m *ChallengeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChallengeBuf.Unmarshal(m, b)
}
func (m *ChallengeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChallengeBuf.Marshal(b, m, deterministic)
}
func (m *ChallengeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeBuf.Merge(m, src)
}
func (m *ChallengeBuf) XXX_Size() int {
	return xxx_messageInfo_ChallengeBuf.Size(m)
}
func (m *ChallengeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeBuf proto.InternalMessageInfo

func (m *ChallengeBuf) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ChallengeBuf) GetAsserter() string {
	if m != nil {
		return m.Asserter
	}
	return ""
}

func (m *ChallengeBuf) GetChallenger() string {
	if m != nil {
		return m.Challenger
	}
	return ""
}

func (m *ChallengeBuf) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

type DisputableNodeBuf struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Deadline             string   `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisputableNodeBuf) Reset()         { *m = DisputableNodeBuf{} }
func (m *DisputableNodeBuf) String() string { return proto.CompactTextString(m) }
func (*DisputableNodeBuf) ProtoMessage()    {}
func (*DisputableNodeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{5}
}

func (m *DisputableNodeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisputableNodeBuf.Unmarshal(m, b)
}
func (m *DisputableNodeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisputableNodeBuf.Marshal(b, m, deterministic)
}
func (m *DisputableNodeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisputableNodeBuf.Merge(m, src)
}
func (m *DisputableNodeBuf) XXX_Size() int {
	return xxx_messageInfo_DisputableNodeBuf.Size(m)
}
func (m *DisputableNodeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_DisputableNodeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_DisputableNodeBuf proto.InternalMessageInfo

func (m *DisputableNodeBuf) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *DisputableNodeBuf) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

type PendingInboxBuf struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingInboxBuf) Reset()         { *m = PendingInboxBuf{} }
func (m *PendingInboxBuf) String() string { return proto.CompactTextString(m) }
func (*PendingInboxBuf) ProtoMessage()    {}
func (*PendingInboxBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_037f188b50610c79, []int{6}
}

func (m *PendingInboxBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingInboxBuf.Unmarshal(m, b)
}
func (m *PendingInboxBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingInboxBuf.Marshal(b, m, deterministic)
}
func (m *PendingInboxBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingInboxBuf.Merge(m, src)
}
func (m *PendingInboxBuf) XXX_Size() int {
	return xxx_messageInfo_PendingInboxBuf.Size(m)
}
func (m *PendingInboxBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingInboxBuf.DiscardUnknown(m)
}

var xxx_messageInfo_PendingInboxBuf proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChainBuf)(nil), "rollup.ChainBuf")
	proto.RegisterType((*ChainParamsBuf)(nil), "rollup.ChainParamsBuf")
	proto.RegisterType((*NodeBuf)(nil), "rollup.NodeBuf")
	proto.RegisterType((*StakerBuf)(nil), "rollup.StakerBuf")
	proto.RegisterType((*ChallengeBuf)(nil), "rollup.ChallengeBuf")
	proto.RegisterType((*DisputableNodeBuf)(nil), "rollup.DisputableNodeBuf")
	proto.RegisterType((*PendingInboxBuf)(nil), "rollup.PendingInboxBuf")
}

func init() { proto.RegisterFile("rollup.proto", fileDescriptor_037f188b50610c79) }

var fileDescriptor_037f188b50610c79 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x96, 0x9b, 0xb6, 0x49, 0x4e, 0xd2, 0xf6, 0xcf, 0xfc, 0x08, 0x4c, 0x17, 0x28, 0xb2, 0x40,
	0x8a, 0xb8, 0x34, 0x28, 0xb0, 0x43, 0x42, 0xb4, 0x05, 0x09, 0x36, 0xa8, 0x72, 0xbb, 0x62, 0x37,
	0xf6, 0x1c, 0xc7, 0xa3, 0xd8, 0x33, 0x66, 0x66, 0x5c, 0x15, 0x5e, 0x81, 0x37, 0x62, 0xcd, 0x86,
	0xb7, 0x42, 0x33, 0xbe, 0xc8, 0x4e, 0xba, 0x9b, 0xf3, 0x7d, 0xe7, 0x7e, 0x3e, 0x1b, 0xa6, 0x4a,
	0x66, 0x59, 0x59, 0x9c, 0x15, 0x4a, 0x1a, 0x49, 0x0e, 0x2b, 0x2b, 0xf8, 0xb3, 0x07, 0xa3, 0xcb,
	0x94, 0x72, 0x71, 0x51, 0x26, 0x64, 0x01, 0x27, 0xb1, 0x14, 0x46, 0xd1, 0xd8, 0x9c, 0x33, 0xa6,
	0x50, 0x6b, 0xdf, 0x9b, 0x7b, 0x8b, 0x71, 0xb8, 0x0d, 0x93, 0x15, 0x8c, 0x6e, 0xf3, 0x2b, 0xaa,
	0x68, 0xae, 0xfd, 0xbd, 0xb9, 0xb7, 0x98, 0xac, 0x1e, 0x9e, 0xd5, 0xf9, 0x5d, 0xb6, 0x8a, 0xba,
	0x28, 0x93, 0xb0, 0xf5, 0x23, 0xcf, 0xe0, 0x40, 0x48, 0x86, 0xda, 0x1f, 0xcc, 0x07, 0x8b, 0xc9,
	0xea, 0xa4, 0x09, 0xf8, 0x2a, 0x19, 0x5a, 0xcf, 0x8a, 0x25, 0xaf, 0xe1, 0xff, 0x8c, 0x1a, 0xd4,
	0xe6, 0x52, 0x8a, 0x84, 0xab, 0x1c, 0xd9, 0x67, 0xaa, 0x53, 0x7f, 0xdf, 0x35, 0x72, 0x1f, 0x45,
	0x9e, 0x00, 0x64, 0x48, 0x13, 0xfb, 0x46, 0xed, 0x1f, 0xcc, 0x07, 0x8b, 0x71, 0xd8, 0x41, 0xc8,
	0x0b, 0x18, 0x6a, 0x43, 0x37, 0xa8, 0xb4, 0x7f, 0xe8, 0x4a, 0xcf, 0x9a, 0xd2, 0xd7, 0x0e, 0xb6,
	0xc5, 0x1b, 0x0f, 0xf2, 0x16, 0x20, 0x4e, 0x69, 0x96, 0xa1, 0x58, 0xa3, 0xf6, 0x87, 0xce, 0xff,
	0x41, 0x67, 0xb6, 0x8a, 0xb1, 0x21, 0x1d, 0xbf, 0xe0, 0xaf, 0x07, 0xc7, 0xfd, 0xc1, 0xc9, 0x73,
	0xf8, 0xcf, 0xe5, 0x0c, 0xf1, 0x7b, 0xc9, 0x15, 0xe6, 0x28, 0x4c, 0xbd, 0xcd, 0x1d, 0x9c, 0xcc,
	0x61, 0xb2, 0x56, 0x34, 0xc6, 0x2b, 0x54, 0x5c, 0x32, 0xb7, 0xd1, 0xa3, 0xb0, 0x0b, 0x91, 0x97,
	0x30, 0xcb, 0xe9, 0xdd, 0xa7, 0x3b, 0x8c, 0x4b, 0xc3, 0xa5, 0xb8, 0x36, 0x58, 0xd8, 0x45, 0x5a,
	0xbf, 0x5d, 0x82, 0xbc, 0x83, 0x69, 0x81, 0x82, 0x71, 0xb1, 0xfe, 0x22, 0x22, 0x79, 0xe7, 0x96,
	0x37, 0x59, 0x3d, 0x6a, 0xc6, 0xb8, 0xea, 0x70, 0x76, 0x92, 0x9e, 0x73, 0xf0, 0xdb, 0x83, 0x61,
	0x7d, 0x13, 0x42, 0x60, 0x3f, 0xb5, 0xdb, 0xaf, 0x1a, 0x77, 0x6f, 0x72, 0x0e, 0xc7, 0x8c, 0xeb,
	0xa2, 0x34, 0x34, 0xca, 0xd0, 0x3a, 0xd6, 0x0a, 0x78, 0xdc, 0xa4, 0xff, 0xd8, 0x63, 0x6d, 0x81,
	0xad, 0x00, 0x3b, 0x6f, 0x4e, 0xe3, 0x94, 0x0b, 0x74, 0xb7, 0x1d, 0xb8, 0xec, 0x5d, 0x88, 0x9c,
	0xc2, 0x28, 0xe3, 0x62, 0x73, 0xf3, 0xa3, 0x40, 0xd7, 0xfd, 0x51, 0xd8, 0xda, 0x96, 0x2b, 0x14,
	0xde, 0xba, 0xd0, 0x03, 0x17, 0xda, 0xda, 0xc1, 0x2f, 0x0f, 0xc6, 0xed, 0x55, 0x89, 0x0f, 0x43,
	0xda, 0x13, 0x72, 0x63, 0xba, 0xfc, 0x32, 0xa6, 0x76, 0x65, 0xae, 0xfd, 0x71, 0xd8, 0xda, 0x24,
	0x80, 0x69, 0xac, 0xd0, 0xbd, 0x6f, 0x78, 0x8e, 0x75, 0x7b, 0x3d, 0x8c, 0x3c, 0x85, 0xa3, 0xf6,
	0xfc, 0xf6, 0xa3, 0xa8, 0xf5, 0xd9, 0x07, 0x83, 0x9f, 0x30, 0xed, 0x4a, 0xc6, 0x56, 0x6d, 0xbe,
	0xa4, 0xba, 0xa1, 0xd6, 0xb6, 0x1c, 0xd5, 0x1a, 0x95, 0x41, 0xd5, 0x74, 0xd4, 0xd8, 0x56, 0xe1,
	0x6d, 0x62, 0x55, 0xf7, 0xd3, 0x41, 0xec, 0x99, 0x36, 0x5c, 0xb0, 0x7a, 0x53, 0xee, 0x1d, 0x5c,
	0xc2, 0x6c, 0xe7, 0x10, 0xf7, 0xde, 0xf3, 0x14, 0x46, 0x0c, 0x29, 0xcb, 0xb8, 0xc0, 0xa6, 0x70,
	0x63, 0x07, 0x33, 0x38, 0xd9, 0x12, 0xcb, 0xc5, 0x87, 0x6f, 0xef, 0xd7, 0xdc, 0xa4, 0x65, 0x74,
	0x16, 0xcb, 0x7c, 0x29, 0x93, 0x24, 0xb6, 0xba, 0xcf, 0x68, 0xa4, 0x97, 0x54, 0x45, 0xdc, 0xa8,
	0x32, 0x5f, 0x16, 0x34, 0xde, 0xd0, 0x35, 0x3a, 0xe4, 0xd5, 0x2d, 0xcd, 0x38, 0xa3, 0x46, 0xaa,
	0x65, 0xa5, 0x8f, 0xe8, 0xd0, 0xfd, 0x82, 0xde, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xea,
	0x37, 0xaa, 0x92, 0x04, 0x00, 0x00,
}
