// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	value "github.com/offchainlabs/arbitrum/packages/arb-util/value"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenTypeBuf struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenTypeBuf) Reset()         { *m = TokenTypeBuf{} }
func (m *TokenTypeBuf) String() string { return proto.CompactTextString(m) }
func (*TokenTypeBuf) ProtoMessage()    {}
func (*TokenTypeBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *TokenTypeBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTypeBuf.Unmarshal(m, b)
}
func (m *TokenTypeBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTypeBuf.Marshal(b, m, deterministic)
}
func (m *TokenTypeBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTypeBuf.Merge(m, src)
}
func (m *TokenTypeBuf) XXX_Size() int {
	return xxx_messageInfo_TokenTypeBuf.Size(m)
}
func (m *TokenTypeBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTypeBuf.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTypeBuf proto.InternalMessageInfo

func (m *TokenTypeBuf) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AddressBuf struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressBuf) Reset()         { *m = AddressBuf{} }
func (m *AddressBuf) String() string { return proto.CompactTextString(m) }
func (*AddressBuf) ProtoMessage()    {}
func (*AddressBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *AddressBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBuf.Unmarshal(m, b)
}
func (m *AddressBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBuf.Marshal(b, m, deterministic)
}
func (m *AddressBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBuf.Merge(m, src)
}
func (m *AddressBuf) XXX_Size() int {
	return xxx_messageInfo_AddressBuf.Size(m)
}
func (m *AddressBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBuf.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBuf proto.InternalMessageInfo

func (m *AddressBuf) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type MessageBuf struct {
	Value                *value.ValueBuf      `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	TokenType            *TokenTypeBuf        `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Amount               *value.BigIntegerBuf `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender               *AddressBuf          `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageBuf) Reset()         { *m = MessageBuf{} }
func (m *MessageBuf) String() string { return proto.CompactTextString(m) }
func (*MessageBuf) ProtoMessage()    {}
func (*MessageBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *MessageBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBuf.Unmarshal(m, b)
}
func (m *MessageBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBuf.Marshal(b, m, deterministic)
}
func (m *MessageBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBuf.Merge(m, src)
}
func (m *MessageBuf) XXX_Size() int {
	return xxx_messageInfo_MessageBuf.Size(m)
}
func (m *MessageBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBuf.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBuf proto.InternalMessageInfo

func (m *MessageBuf) GetValue() *value.ValueBuf {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MessageBuf) GetTokenType() *TokenTypeBuf {
	if m != nil {
		return m.TokenType
	}
	return nil
}

func (m *MessageBuf) GetAmount() *value.BigIntegerBuf {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *MessageBuf) GetSender() *AddressBuf {
	if m != nil {
		return m.Sender
	}
	return nil
}

type TimeBoundsBuf struct {
	StartTime            uint64   `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              uint64   `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeBoundsBuf) Reset()         { *m = TimeBoundsBuf{} }
func (m *TimeBoundsBuf) String() string { return proto.CompactTextString(m) }
func (*TimeBoundsBuf) ProtoMessage()    {}
func (*TimeBoundsBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *TimeBoundsBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeBoundsBuf.Unmarshal(m, b)
}
func (m *TimeBoundsBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeBoundsBuf.Marshal(b, m, deterministic)
}
func (m *TimeBoundsBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeBoundsBuf.Merge(m, src)
}
func (m *TimeBoundsBuf) XXX_Size() int {
	return xxx_messageInfo_TimeBoundsBuf.Size(m)
}
func (m *TimeBoundsBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeBoundsBuf.DiscardUnknown(m)
}

var xxx_messageInfo_TimeBoundsBuf proto.InternalMessageInfo

func (m *TimeBoundsBuf) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TimeBoundsBuf) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type BalanceTrackerBuf struct {
	Types                []*TokenTypeBuf        `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Amounts              []*value.BigIntegerBuf `protobuf:"bytes,2,rep,name=amounts,proto3" json:"amounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BalanceTrackerBuf) Reset()         { *m = BalanceTrackerBuf{} }
func (m *BalanceTrackerBuf) String() string { return proto.CompactTextString(m) }
func (*BalanceTrackerBuf) ProtoMessage()    {}
func (*BalanceTrackerBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *BalanceTrackerBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceTrackerBuf.Unmarshal(m, b)
}
func (m *BalanceTrackerBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceTrackerBuf.Marshal(b, m, deterministic)
}
func (m *BalanceTrackerBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceTrackerBuf.Merge(m, src)
}
func (m *BalanceTrackerBuf) XXX_Size() int {
	return xxx_messageInfo_BalanceTrackerBuf.Size(m)
}
func (m *BalanceTrackerBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceTrackerBuf.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceTrackerBuf proto.InternalMessageInfo

func (m *BalanceTrackerBuf) GetTypes() []*TokenTypeBuf {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *BalanceTrackerBuf) GetAmounts() []*value.BigIntegerBuf {
	if m != nil {
		return m.Amounts
	}
	return nil
}

type PreconditionBuf struct {
	BeforeHash           *value.HashBuf     `protobuf:"bytes,1,opt,name=beforeHash,proto3" json:"beforeHash,omitempty"`
	TimeBounds           *TimeBoundsBuf     `protobuf:"bytes,2,opt,name=timeBounds,proto3" json:"timeBounds,omitempty"`
	BalanceTracker       *BalanceTrackerBuf `protobuf:"bytes,3,opt,name=balanceTracker,proto3" json:"balanceTracker,omitempty"`
	BeforeInbox          *value.HashBuf     `protobuf:"bytes,4,opt,name=beforeInbox,proto3" json:"beforeInbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PreconditionBuf) Reset()         { *m = PreconditionBuf{} }
func (m *PreconditionBuf) String() string { return proto.CompactTextString(m) }
func (*PreconditionBuf) ProtoMessage()    {}
func (*PreconditionBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *PreconditionBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreconditionBuf.Unmarshal(m, b)
}
func (m *PreconditionBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreconditionBuf.Marshal(b, m, deterministic)
}
func (m *PreconditionBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreconditionBuf.Merge(m, src)
}
func (m *PreconditionBuf) XXX_Size() int {
	return xxx_messageInfo_PreconditionBuf.Size(m)
}
func (m *PreconditionBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_PreconditionBuf.DiscardUnknown(m)
}

var xxx_messageInfo_PreconditionBuf proto.InternalMessageInfo

func (m *PreconditionBuf) GetBeforeHash() *value.HashBuf {
	if m != nil {
		return m.BeforeHash
	}
	return nil
}

func (m *PreconditionBuf) GetTimeBounds() *TimeBoundsBuf {
	if m != nil {
		return m.TimeBounds
	}
	return nil
}

func (m *PreconditionBuf) GetBalanceTracker() *BalanceTrackerBuf {
	if m != nil {
		return m.BalanceTracker
	}
	return nil
}

func (m *PreconditionBuf) GetBeforeInbox() *value.HashBuf {
	if m != nil {
		return m.BeforeInbox
	}
	return nil
}

type AssertionBuf struct {
	AfterHash            *value.HashBuf    `protobuf:"bytes,1,opt,name=afterHash,proto3" json:"afterHash,omitempty"`
	NumSteps             uint32            `protobuf:"varint,2,opt,name=numSteps,proto3" json:"numSteps,omitempty"`
	Messages             []*MessageBuf     `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Logs                 []*value.ValueBuf `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AssertionBuf) Reset()         { *m = AssertionBuf{} }
func (m *AssertionBuf) String() string { return proto.CompactTextString(m) }
func (*AssertionBuf) ProtoMessage()    {}
func (*AssertionBuf) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *AssertionBuf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssertionBuf.Unmarshal(m, b)
}
func (m *AssertionBuf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssertionBuf.Marshal(b, m, deterministic)
}
func (m *AssertionBuf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssertionBuf.Merge(m, src)
}
func (m *AssertionBuf) XXX_Size() int {
	return xxx_messageInfo_AssertionBuf.Size(m)
}
func (m *AssertionBuf) XXX_DiscardUnknown() {
	xxx_messageInfo_AssertionBuf.DiscardUnknown(m)
}

var xxx_messageInfo_AssertionBuf proto.InternalMessageInfo

func (m *AssertionBuf) GetAfterHash() *value.HashBuf {
	if m != nil {
		return m.AfterHash
	}
	return nil
}

func (m *AssertionBuf) GetNumSteps() uint32 {
	if m != nil {
		return m.NumSteps
	}
	return 0
}

func (m *AssertionBuf) GetMessages() []*MessageBuf {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *AssertionBuf) GetLogs() []*value.ValueBuf {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenTypeBuf)(nil), "protocol.TokenTypeBuf")
	proto.RegisterType((*AddressBuf)(nil), "protocol.AddressBuf")
	proto.RegisterType((*MessageBuf)(nil), "protocol.MessageBuf")
	proto.RegisterType((*TimeBoundsBuf)(nil), "protocol.TimeBoundsBuf")
	proto.RegisterType((*BalanceTrackerBuf)(nil), "protocol.BalanceTrackerBuf")
	proto.RegisterType((*PreconditionBuf)(nil), "protocol.PreconditionBuf")
	proto.RegisterType((*AssertionBuf)(nil), "protocol.AssertionBuf")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0x95, 0xdd, 0x6d, 0xbb, 0x3b, 0xdd, 0x6e, 0x55, 0xab, 0x82, 0xa8, 0x70, 0xa8, 0x02,
	0x48, 0x1c, 0x96, 0xa4, 0x02, 0x24, 0x0e, 0x88, 0x43, 0xc3, 0x01, 0x7a, 0x40, 0x42, 0x61, 0xc5,
	0x81, 0x9b, 0x93, 0x4c, 0xb2, 0xd1, 0x26, 0x76, 0xb0, 0x1d, 0x44, 0x9f, 0x8a, 0xa7, 0xe0, 0x81,
	0x78, 0x03, 0x64, 0xc7, 0xf9, 0xa0, 0xa5, 0xbd, 0x58, 0x9e, 0x99, 0xdf, 0x7c, 0xfc, 0x3d, 0x86,
	0x55, 0x2d, 0xb8, 0xe2, 0x09, 0x2f, 0x7d, 0x73, 0x21, 0xf3, 0xce, 0x3e, 0x3b, 0xf9, 0x41, 0xcb,
	0x06, 0x03, 0x73, 0xb6, 0x41, 0xef, 0x29, 0x2c, 0x37, 0x7c, 0x87, 0x6c, 0x73, 0x5d, 0x63, 0xd8,
	0x64, 0xe4, 0x14, 0xf6, 0x4c, 0xd8, 0x75, 0xce, 0x9d, 0xe7, 0xcb, 0xa8, 0x35, 0x3c, 0x0f, 0xe0,
	0x32, 0x4d, 0x05, 0x4a, 0x79, 0x37, 0xf3, 0xdb, 0x01, 0xf8, 0x84, 0x52, 0xd2, 0xdc, 0x14, 0x7a,
	0x36, 0x86, 0x0e, 0x5f, 0x1e, 0xfb, 0x6d, 0xd7, 0xaf, 0xfa, 0x0c, 0x9b, 0xcc, 0x66, 0x91, 0xd7,
	0xb0, 0x50, 0x5d, 0x7f, 0x77, 0x62, 0xd0, 0x07, 0x7e, 0x2f, 0x60, 0x3c, 0x5a, 0x34, 0x80, 0x64,
	0x0d, 0xfb, 0xb4, 0xe2, 0x0d, 0x53, 0xee, 0xd4, 0xa4, 0x9c, 0xda, 0xea, 0x61, 0x91, 0x5f, 0x31,
	0x85, 0x39, 0x0a, 0x9d, 0x60, 0x19, 0x4d, 0x4b, 0x64, 0x29, 0x0a, 0x77, 0x66, 0xe9, 0xbe, 0xc1,
	0xa0, 0x2a, 0xb2, 0x8c, 0xf7, 0x01, 0x8e, 0x36, 0x45, 0x85, 0x21, 0x6f, 0x58, 0x6a, 0xe4, 0x3e,
	0x86, 0x85, 0x54, 0x54, 0x28, 0xed, 0x35, 0x6a, 0x66, 0xd1, 0xe0, 0x20, 0x2e, 0x1c, 0x20, 0x4b,
	0x4d, 0x6c, 0x62, 0x62, 0x9d, 0xe9, 0x7d, 0x87, 0x93, 0x90, 0x96, 0x94, 0x25, 0xb8, 0x11, 0x34,
	0xd9, 0x99, 0x99, 0xc8, 0x1a, 0xf6, 0xd4, 0x75, 0x8d, 0xd2, 0x75, 0xce, 0xa7, 0xf7, 0x68, 0x6d,
	0x21, 0xe2, 0xc3, 0x41, 0xab, 0x41, 0xba, 0x13, 0xc3, 0xff, 0x5f, 0x68, 0x07, 0x79, 0x7f, 0x1c,
	0x38, 0xfe, 0x2c, 0x30, 0xe1, 0x2c, 0x2d, 0x54, 0xc1, 0x99, 0xee, 0xe8, 0x03, 0xc4, 0x98, 0x71,
	0x81, 0x1f, 0xa9, 0xdc, 0xda, 0x6d, 0xac, 0x6c, 0x19, 0xed, 0xd2, 0x05, 0x46, 0x04, 0x79, 0x03,
	0xa0, 0x7a, 0xfd, 0x76, 0x25, 0x0f, 0x47, 0x63, 0x8e, 0xdf, 0x26, 0x1a, 0xa1, 0xe4, 0x3d, 0xac,
	0xe2, 0x7f, 0xf4, 0xda, 0xe5, 0x3c, 0x1a, 0x92, 0x6f, 0xbd, 0x47, 0x74, 0x23, 0x85, 0x5c, 0xc0,
	0x61, 0x3b, 0xcb, 0x15, 0x8b, 0xf9, 0x4f, 0xbb, 0xb0, 0x9b, 0xe3, 0x8e, 0x11, 0xef, 0x97, 0x03,
	0xcb, 0x4b, 0x29, 0x51, 0x74, 0x82, 0xd7, 0xb0, 0xa0, 0x99, 0x42, 0x71, 0x8f, 0xde, 0x01, 0x20,
	0x67, 0x30, 0x67, 0x4d, 0xf5, 0x45, 0x61, 0xdd, 0x8a, 0x3d, 0x8a, 0x7a, 0x9b, 0x5c, 0xc0, 0xbc,
	0x6a, 0x7f, 0xb4, 0x74, 0xa7, 0xf6, 0xfd, 0x7b, 0x2d, 0xc3, 0x5f, 0x8f, 0x7a, 0x8a, 0x3c, 0x81,
	0x59, 0xc9, 0x73, 0xe9, 0xce, 0x0c, 0x7d, 0xeb, 0xd3, 0x9b, 0x60, 0xf8, 0xee, 0xdb, 0xdb, 0xbc,
	0x50, 0xdb, 0x26, 0xf6, 0x13, 0x5e, 0x05, 0x3c, 0xcb, 0x92, 0x2d, 0x2d, 0x58, 0x49, 0x63, 0x19,
	0x50, 0x11, 0x17, 0x4a, 0x34, 0x55, 0x50, 0xd3, 0x64, 0xa7, 0x2b, 0x6a, 0xcf, 0x8b, 0x46, 0x15,
	0x65, 0xd0, 0x35, 0x8e, 0xf7, 0xcd, 0xed, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xb3,
	0xa6, 0x90, 0xe8, 0x03, 0x00, 0x00,
}
