#!/bin/bash
### --------------------------------------------------------------------
### install-deps
### --------------------------------------------------------------------
docker build -t arb-node -f packages/arb-node.Dockerfile packages