#!/bin/bash

# Exit on error
set -e

cd packages

cd arb-util
go generate ./...
cd ..

cd arb-avm-cpp
go generate ./...
cd ..

cd arb-validator-core
go generate ./...
cd ..

cd arb-validator
go generate ./...
cd ..

cd arb-provider-go
go generate ./...
cd ..

cd arb-evm
go generate ./...
cd ..

cd arb-tx-aggregator
go generate ./...
cd ..
