#!/bin/bash

# Exit on error
set -e

cd packages

cd arb-util
go vet ./...
cd ..

cd arb-avm-cpp
go vet ./...
cd ..

cd arb-validator-core
go vet ./...
cd ..

cd arb-validator
go vet ./...
cd ..

cd arb-evm
go vet ./...
cd ..

cd arb-checkpointer
go vet ./...
cd ..

cd arb-tx-aggregator
go vet ./...
cd ..
