#!/bin/bash

# Exit on error
set -e

packages=(
    arb-util
    arb-avm-cpp
    arb-validator-core
    arb-validator
    arb-evm
    arb-checkpointer
    arb-tx-aggregator
)

cd packages

for i in "${packages[@]}"; do
    cd $i
    go vet ./...
    cd ..
done
