#!/bin/sh
### --------------------------------------------------------------------
### install-arb-validator
### --------------------------------------------------------------------

# Step 1: build arb-avm-cpp
mkdir -p packages/arb-avm-cpp/build
cd packages/arb-avm-cpp/build
conan install ..
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build . -j4
cp lib/lib* ../cmachine/
cd ../../..

# Step 2: build and install arb-validator
cd packages/arb-validator
go install -v ./...
