#!/bin/bash
### --------------------------------------------------------------------
### install-deps
### --------------------------------------------------------------------

# When running `pip3 install --user ...` the bin location is in:
# python3 -c "import site; print(site.USER_BASE + '/bin')"

# Exit on error
set -e

pip3 install -r requirements.txt --user
pip3 install -r requirements-dev.txt --user

# Setup pre-commit
python3 -m pre_commit install

# Install arb-compiler-evm
cd packages/arb-compiler-evm
pip3 install -r requirements.txt --user
sudo python3 setup.py develop # TODO: may need sudo or --user here!
cd ../..
