#!/bin/bash
### --------------------------------------------------------------------
### install-ci
### --------------------------------------------------------------------

# Exit on error
set -e

. vconan/bin/activate
mkdir -p packages/arb-avm-cpp/ci
cd packages/arb-avm-cpp/ci
conan install .. -s compiler.libcxx=libstdc++11
deactivate
cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=True ..
cmake --build . -j $(nproc)
cd ../../..

# Install arb-compiler-evm
cd packages/arb-compiler-evm
pip3 install -r requirements.txt --user
python3 setup.py install --user
cd ../..
