#!/bin/sh
### --------------------------------------------------------------------
### install
### NOTE: invoke from the monorepo root directory
### --------------------------------------------------------------------

# Install conan
if ! conan >/dev/null 2>&1; then
    pip3 install conan
fi

# conan nonstd-lite
if ! conan remote list | grep -q "nonstd-lite"; then
    conan remote add nonstd-lite https://api.bintray.com/conan/martinmoene/nonstd-lite
fi;

# Install arb-deploy
cd scripts/arb-deploy
#python3 setup.py -q develop
cd ../..

# Install arb-compiler-evm
cd packages/arb-compiler-evm
#pip3 install -r requirements.txt -q
#python3 setup.py -q develop
cd ../..

# Install arb-avm-cpp
mkdir -p packages/arb-avm-cpp/build
cd packages/arb-avm-cpp/build
conan install ..
if [ $# -ge 1 ]; then
    cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=True -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
else
    cmake -DCMAKE_BUILD_TYPE=Release -DCODE_COVERAGE=False ..
fi
if nproc >/dev/null 2>&1; then
    NPROC=$(nproc)
elif sysctl -n hw.ncpu >/dev/null 2>&1; then
    NPROC=$(sysctl -n hw.ncpu)
else
    NPROC=4
fi
cmake --build . "-j${NPROC}"
cp lib/lib* ../cmachine/
cd ../../..

# install arb-validator
cd packages/arb-validator
go install -v ./...
