#!/bin/sh
### --------------------------------------------------------------------
### install-ci
### --------------------------------------------------------------------

mkdir -p packages/arb-avm-cpp/ci
cd packages/arb-avm-cpp/ci
source ../../../vconan/bin/activate
conan install .. -s compiler.libcxx=libstdc++11
deactivate
cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=True ..
cmake --build . -j $(nproc)
cd ../../..
