#!/bin/bash
### --------------------------------------------------------------------
### install-deps
### --------------------------------------------------------------------

# When running `pip3 install --user ...` the bin location is in:
# python3 -c "import site; print(site.USER_BASE + '/bin')"

# Exit on error
set -e

pip3 install -r requirements.txt --user
pip3 install -r requirements-dev.txt --user

# Setup pre-commit
python3 -m pre_commit install

# Install conan
VIRTUALENV_MAJOR_VERSION=$(pip3 show virtualenv | grep Version | sed 's/.*: //' | sed -n 's/\..*//p')
if (($VIRTUALENV_MAJOR_VERSION < 20))
then
    python3 -m virtualenv --no-site-packages vconan
else
    python3 -m virtualenv vconan
fi
. vconan/bin/activate
pip3 install --upgrade conan
# conan nonstd-lite
if ! conan remote list | grep -q "nonstd-lite"; then
    conan remote add nonstd-lite https://api.bintray.com/conan/martinmoene/nonstd-lite
fi;
deactivate

# Install arb-compiler-evm
cd packages/arb-compiler-evm
pip3 install -r requirements.txt --user
sudo python3 setup.py develop # TODO: may need sudo or --user here!
cd ../..
