#!/bin/bash
### --------------------------------------------------------------------
### update-go-abi
### --------------------------------------------------------------------

cd packages/arb-bridge-eth/contracts
cp -r ../node_modules/@openzeppelin/ ./@openzeppelin
cp -r ../installed_contracts/bytes/ ./bytes

abigen --sol=vm/ArbFactory.sol --pkg=arbfactory --out=arbfactory.go
abigen --sol=vm/ArbRollup.sol --pkg=rollup --out=arbrollup.go

abigen --sol=challenge/ChallengeFactory.sol --pkg=challengefactory --out=challengefactory.go
abigen --sol=challenge/PendingTopChallenge.sol --pkg=pendingtopchallenge --out=pendingtopchallenge.go
abigen --sol=challenge/MessagesChallenge.sol --pkg=messageschallenge --out=messageschallenge.go
abigen --sol=challenge/ExecutionChallenge.sol --pkg=executionchallenge --out=executionchallenge.go

abigen --sol=GlobalPendingInbox.sol --pkg=globalpendinginbox --out=globalpendinginbox.go

abigen --sol=test_only/ChallengeTester.sol --pkg=challengetester --out=challengetester.go
abigen --sol=test_only/MessageTester.sol --pkg=messagetester --out=messagetester.go

\cp arbfactory.go ../../arb-validator/ethbridge/arbfactory/
\cp arbrollup.go ../../arb-validator/ethbridge/rollup/
\cp challengefactory.go ../../arb-validator/ethbridge/challengefactory/
\cp pendingtopchallenge.go ../../arb-validator/ethbridge/pendingtopchallenge/
\cp messageschallenge.go ../../arb-validator/ethbridge/messageschallenge/
\cp executionchallenge.go ../../arb-validator/ethbridge/executionchallenge/
\cp globalpendinginbox.go ../../arb-validator/ethbridge/globalpendinginbox/
\cp challengetester.go ../../arb-validator/ethbridge/challengetester/
\cp messagetester.go ../../arb-validator/ethbridge/messagetester/
rm -rf @openzeppelin bytes
rm -f arbfactory.go arbrollup.go
rm -f challengefactory.go
rm -f pendingtopchallenge.go messageschallenge.go executionchallenge.go
rm -f globalpendinginbox.go
rm -f challengetester.go messagetester.go
cd ../../..
yarn workspace arb-provider-ethers update-abi
