#!/bin/bash
### --------------------------------------------------------------------
### update-go-abi
### --------------------------------------------------------------------

cd packages/arb-bridge-eth/contracts

abigen --sol=vm/ArbFactory.sol --pkg=arbfactory --out=arbfactory.go
abigen --sol=vm/ArbRollup.sol --pkg=rollup --out=arbrollup.go

abigen --sol=challenge/ChallengeFactory.sol --pkg=challengefactory --out=challengefactory.go
abigen --sol=challenge/InboxTopChallenge.sol --pkg=inboxtopchallenge --out=inboxtopchallenge.go
abigen --sol=challenge/MessagesChallenge.sol --pkg=messageschallenge --out=messageschallenge.go
abigen --sol=challenge/ExecutionChallenge.sol --pkg=executionchallenge --out=executionchallenge.go

abigen --sol=GlobalInbox.sol --pkg=globalinbox --out=globalinbox.go

abigen --sol=test_only/ChallengeTester.sol --pkg=challengetester --out=challengetester.go
abigen --sol=test_only/MessageTester.sol --pkg=messagetester --out=messagetester.go
abigen --sol=test_only/SigUtilsTester.sol --pkg=sigutilstester --out=sigutilstester.go
abigen --sol=test_only/ValueTester.sol --pkg=valuetester --out=valuetester.go
abigen --sol=test_only/ProtocolTester.sol --pkg=protocoltester --out=protocoltester.go
abigen --sol=test_only/MachineTester.sol --pkg=machinetester --out=machinetester.go
abigen --sol=test_only/RollupTester.sol --pkg=rolluptester --out=rolluptester.go
abigen --sol=test_only/OneStepProofTester.sol --pkg=onestepprooftester --out=onestepprooftester.go

\mv arbfactory.go ../../arb-validator-core/ethbridge/arbfactory/
\mv arbrollup.go ../../arb-validator-core/ethbridge/rollup/
\mv challengefactory.go ../../arb-validator-core/ethbridge/challengefactory/
\mv inboxtopchallenge.go ../../arb-validator-core/ethbridge/inboxtopchallenge/
\mv messageschallenge.go ../../arb-validator-core/ethbridge/messageschallenge/
\mv executionchallenge.go ../../arb-validator-core/ethbridge/executionchallenge/
\mv globalinbox.go ../../arb-validator-core/ethbridge/globalinbox/
\mv challengetester.go ../../arb-validator-core/ethbridgetest/challengetester/
\mv messagetester.go ../../arb-validator-core/ethbridgetest/messagetester/
\mv sigutilstester.go ../../arb-validator-core/ethbridgetest/sigutilstester/
\mv valuetester.go ../../arb-validator-core/ethbridgetest/valuetester/
\mv protocoltester.go ../../arb-validator-core/ethbridgetest/protocoltester/
\mv machinetester.go ../../arb-validator/proofmachine/machinetester/
\mv rolluptester.go ../../arb-validator-core/ethbridgetest/rolluptester/
\mv onestepprooftester.go ../../arb-validator-core/ethbridgetest/onestepprooftester/

cd ../../..

yarn workspace arb-provider-ethers update-abi
cd packages/arb-compiler-evm/contract-templates/contracts
abigen --sol=ArbSys.sol --pkg=goarbitrum --out=arbsys.go
abigen --sol=ArbInfo.sol --pkg=goarbitrum --out=arbinfo.go

\cp arbsys.go arbinfo.go ../../../../packages/arb-provider-go/
rm -f arbsys.go arbinfo.go
