/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface BridgeCreatorInterface extends ethers.utils.Interface {
  functions: {
    'createBridge(address,address,address,uint256,uint256)': FunctionFragment
    'owner()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'updateTemplates(address,address,address,address,address)': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'createBridge',
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'updateTemplates',
    values: [string, string, string, string, string]
  ): string

  decodeFunctionResult(
    functionFragment: 'createBridge',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateTemplates',
    data: BytesLike
  ): Result

  events: {
    'OwnershipTransferred(address,address)': EventFragment
    'TemplatesUpdated()': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TemplatesUpdated'): EventFragment
}

export class BridgeCreator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: BridgeCreatorInterface

  functions: {
    createBridge(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'createBridge(address,address,address,uint256,uint256)'(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    'owner()'(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

    'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    updateTemplates(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'updateTemplates(address,address,address,address,address)'(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>
  }

  createBridge(
    adminProxy: string,
    rollup: string,
    sequencer: string,
    sequencerDelayBlocks: BigNumberish,
    sequencerDelaySeconds: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'createBridge(address,address,address,uint256,uint256)'(
    adminProxy: string,
    rollup: string,
    sequencer: string,
    sequencerDelayBlocks: BigNumberish,
    sequencerDelaySeconds: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  'owner()'(overrides?: CallOverrides): Promise<string>

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

  'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'transferOwnership(address)'(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  updateTemplates(
    _delayedBridgeTemplate: string,
    _sequencerInboxTemplate: string,
    _inboxTemplate: string,
    _rollupEventBridgeTemplate: string,
    _outboxTemplate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'updateTemplates(address,address,address,address,address)'(
    _delayedBridgeTemplate: string,
    _sequencerInboxTemplate: string,
    _inboxTemplate: string,
    _rollupEventBridgeTemplate: string,
    _outboxTemplate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  callStatic: {
    createBridge(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, string]>

    'createBridge(address,address,address,uint256,uint256)'(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string, string, string, string]>

    owner(overrides?: CallOverrides): Promise<string>

    'owner()'(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>

    updateTemplates(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: CallOverrides
    ): Promise<void>

    'updateTemplates(address,address,address,address,address)'(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter

    TemplatesUpdated(): EventFilter
  }

  estimateGas: {
    createBridge(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    'createBridge(address,address,address,uint256,uint256)'(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>

    'renounceOwnership()'(overrides?: Overrides): Promise<BigNumber>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    updateTemplates(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'updateTemplates(address,address,address,address,address)'(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<BigNumber>
  }

  populateTransaction: {
    createBridge(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'createBridge(address,address,address,uint256,uint256)'(
      adminProxy: string,
      rollup: string,
      sequencer: string,
      sequencerDelayBlocks: BigNumberish,
      sequencerDelaySeconds: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>

    'renounceOwnership()'(overrides?: Overrides): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    updateTemplates(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'updateTemplates(address,address,address,address,address)'(
      _delayedBridgeTemplate: string,
      _sequencerInboxTemplate: string,
      _inboxTemplate: string,
      _rollupEventBridgeTemplate: string,
      _outboxTemplate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>
  }
}
