/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface EthBatchTokenReceiverInterface extends ethers.utils.Interface {
  functions: {
    'codeHash()': FunctionFragment
    'distributeBatch(bytes32)': FunctionFragment
    'finalizeBuddyDeploy(bool)': FunctionFragment
    'inbox()': FunctionFragment
    'initiateBuddyDeploy(uint256,uint256,uint256,bytes)': FunctionFragment
    'l2Buddy()': FunctionFragment
    'l2Connection()': FunctionFragment
    'l2Deployer()': FunctionFragment
    'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'codeHash', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'distributeBatch',
    values: [BytesLike]
  ): string
  encodeFunctionData(
    functionFragment: 'finalizeBuddyDeploy',
    values: [boolean]
  ): string
  encodeFunctionData(functionFragment: 'inbox', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'initiateBuddyDeploy',
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string
  encodeFunctionData(functionFragment: 'l2Buddy', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'l2Connection',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'l2Deployer', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'redeemWithdrawal',
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike[],
      BytesLike[]
    ]
  ): string

  decodeFunctionResult(functionFragment: 'codeHash', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'distributeBatch',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'finalizeBuddyDeploy',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'inbox', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'initiateBuddyDeploy',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'l2Buddy', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'l2Connection',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'l2Deployer', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'redeemWithdrawal',
    data: BytesLike
  ): Result

  events: {
    'DeployBuddyContract(uint256,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'DeployBuddyContract'): EventFragment
}

export class EthBatchTokenReceiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: EthBatchTokenReceiverInterface

  functions: {
    codeHash(overrides?: CallOverrides): Promise<[string]>

    'codeHash()'(overrides?: CallOverrides): Promise<[string]>

    distributeBatch(
      _root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'distributeBatch(bytes32)'(
      _root: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    finalizeBuddyDeploy(
      success: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'finalizeBuddyDeploy(bool)'(
      success: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    inbox(overrides?: CallOverrides): Promise<[string]>

    'inbox()'(overrides?: CallOverrides): Promise<[string]>

    initiateBuddyDeploy(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>

    'initiateBuddyDeploy(uint256,uint256,uint256,bytes)'(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>

    l2Buddy(overrides?: CallOverrides): Promise<[string]>

    'l2Buddy()'(overrides?: CallOverrides): Promise<[string]>

    l2Connection(overrides?: CallOverrides): Promise<[number]>

    'l2Connection()'(overrides?: CallOverrides): Promise<[number]>

    l2Deployer(overrides?: CallOverrides): Promise<[string]>

    'l2Deployer()'(overrides?: CallOverrides): Promise<[string]>

    redeemWithdrawal(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])'(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>
  }

  codeHash(overrides?: CallOverrides): Promise<string>

  'codeHash()'(overrides?: CallOverrides): Promise<string>

  distributeBatch(
    _root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'distributeBatch(bytes32)'(
    _root: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  finalizeBuddyDeploy(
    success: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'finalizeBuddyDeploy(bool)'(
    success: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  inbox(overrides?: CallOverrides): Promise<string>

  'inbox()'(overrides?: CallOverrides): Promise<string>

  initiateBuddyDeploy(
    maxSubmissionCost: BigNumberish,
    maxGas: BigNumberish,
    gasPriceBid: BigNumberish,
    contractInitCode: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>

  'initiateBuddyDeploy(uint256,uint256,uint256,bytes)'(
    maxSubmissionCost: BigNumberish,
    maxGas: BigNumberish,
    gasPriceBid: BigNumberish,
    contractInitCode: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>

  l2Buddy(overrides?: CallOverrides): Promise<string>

  'l2Buddy()'(overrides?: CallOverrides): Promise<string>

  l2Connection(overrides?: CallOverrides): Promise<number>

  'l2Connection()'(overrides?: CallOverrides): Promise<number>

  l2Deployer(overrides?: CallOverrides): Promise<string>

  'l2Deployer()'(overrides?: CallOverrides): Promise<string>

  redeemWithdrawal(
    dest: string,
    amount: BigNumberish,
    width: BigNumberish,
    index: BigNumberish,
    peaks: BytesLike[],
    siblings: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])'(
    dest: string,
    amount: BigNumberish,
    width: BigNumberish,
    index: BigNumberish,
    peaks: BytesLike[],
    siblings: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  callStatic: {
    codeHash(overrides?: CallOverrides): Promise<string>

    'codeHash()'(overrides?: CallOverrides): Promise<string>

    distributeBatch(_root: BytesLike, overrides?: CallOverrides): Promise<void>

    'distributeBatch(bytes32)'(
      _root: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>

    finalizeBuddyDeploy(
      success: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    'finalizeBuddyDeploy(bool)'(
      success: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    inbox(overrides?: CallOverrides): Promise<string>

    'inbox()'(overrides?: CallOverrides): Promise<string>

    initiateBuddyDeploy(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'initiateBuddyDeploy(uint256,uint256,uint256,bytes)'(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    l2Buddy(overrides?: CallOverrides): Promise<string>

    'l2Buddy()'(overrides?: CallOverrides): Promise<string>

    l2Connection(overrides?: CallOverrides): Promise<number>

    'l2Connection()'(overrides?: CallOverrides): Promise<number>

    l2Deployer(overrides?: CallOverrides): Promise<string>

    'l2Deployer()'(overrides?: CallOverrides): Promise<string>

    redeemWithdrawal(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>

    'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])'(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {
    DeployBuddyContract(
      seqNum: BigNumberish | null,
      l2Address: null
    ): EventFilter
  }

  estimateGas: {
    codeHash(overrides?: CallOverrides): Promise<BigNumber>

    'codeHash()'(overrides?: CallOverrides): Promise<BigNumber>

    distributeBatch(_root: BytesLike, overrides?: Overrides): Promise<BigNumber>

    'distributeBatch(bytes32)'(
      _root: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>

    finalizeBuddyDeploy(
      success: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>

    'finalizeBuddyDeploy(bool)'(
      success: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>

    inbox(overrides?: CallOverrides): Promise<BigNumber>

    'inbox()'(overrides?: CallOverrides): Promise<BigNumber>

    initiateBuddyDeploy(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>

    'initiateBuddyDeploy(uint256,uint256,uint256,bytes)'(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>

    l2Buddy(overrides?: CallOverrides): Promise<BigNumber>

    'l2Buddy()'(overrides?: CallOverrides): Promise<BigNumber>

    l2Connection(overrides?: CallOverrides): Promise<BigNumber>

    'l2Connection()'(overrides?: CallOverrides): Promise<BigNumber>

    l2Deployer(overrides?: CallOverrides): Promise<BigNumber>

    'l2Deployer()'(overrides?: CallOverrides): Promise<BigNumber>

    redeemWithdrawal(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>

    'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])'(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>
  }

  populateTransaction: {
    codeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'codeHash()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    distributeBatch(
      _root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'distributeBatch(bytes32)'(
      _root: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    finalizeBuddyDeploy(
      success: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'finalizeBuddyDeploy(bool)'(
      success: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    inbox(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'inbox()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    initiateBuddyDeploy(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>

    'initiateBuddyDeploy(uint256,uint256,uint256,bytes)'(
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
      contractInitCode: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>

    l2Buddy(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2Buddy()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2Connection(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2Connection()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2Deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2Deployer()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    redeemWithdrawal(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'redeemWithdrawal(address,uint256,uint256,uint256,bytes32[],bytes32[])'(
      dest: string,
      amount: BigNumberish,
      width: BigNumberish,
      index: BigNumberish,
      peaks: BytesLike[],
      siblings: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>
  }
}
