/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface OutboxInterface extends ethers.utils.Interface {
  functions: {
    'beacon()': FunctionFragment
    'bridge()': FunctionFragment
    'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)': FunctionFragment
    'calculateMerkleRoot(bytes32[],uint256,bytes32)': FunctionFragment
    'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)': FunctionFragment
    'initialize(address,address)': FunctionFragment
    'isMaster()': FunctionFragment
    'l2ToL1Block()': FunctionFragment
    'l2ToL1EthBlock()': FunctionFragment
    'l2ToL1Sender()': FunctionFragment
    'l2ToL1Timestamp()': FunctionFragment
    'outboxes(uint256)': FunctionFragment
    'outboxesLength()': FunctionFragment
    'processOutgoingMessages(bytes,uint256[])': FunctionFragment
    'rollup()': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'beacon', values?: undefined): string
  encodeFunctionData(functionFragment: 'bridge', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'calculateItemHash',
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateMerkleRoot',
    values: [BytesLike[], BigNumberish, BytesLike]
  ): string
  encodeFunctionData(
    functionFragment: 'executeTransaction',
    values: [
      BigNumberish,
      BytesLike[],
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [string, string]
  ): string
  encodeFunctionData(functionFragment: 'isMaster', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'l2ToL1Block',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'l2ToL1EthBlock',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'l2ToL1Sender',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'l2ToL1Timestamp',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'outboxes',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'outboxesLength',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'processOutgoingMessages',
    values: [BytesLike, BigNumberish[]]
  ): string
  encodeFunctionData(functionFragment: 'rollup', values?: undefined): string

  decodeFunctionResult(functionFragment: 'beacon', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'bridge', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'calculateItemHash',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateMerkleRoot',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'executeTransaction',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isMaster', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'l2ToL1Block', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'l2ToL1EthBlock',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'l2ToL1Sender',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'l2ToL1Timestamp',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'outboxes', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'outboxesLength',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'processOutgoingMessages',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'rollup', data: BytesLike): Result

  events: {
    'OutBoxTransactionExecuted(address,address,uint256,uint256)': EventFragment
    'OutboxEntryCreated(uint256,uint256,bytes32,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'OutBoxTransactionExecuted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OutboxEntryCreated'): EventFragment
}

export class Outbox extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: OutboxInterface

  functions: {
    beacon(overrides?: CallOverrides): Promise<[string]>

    'beacon()'(overrides?: CallOverrides): Promise<[string]>

    bridge(overrides?: CallOverrides): Promise<[string]>

    'bridge()'(overrides?: CallOverrides): Promise<[string]>

    calculateItemHash(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>

    'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)'(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>

    calculateMerkleRoot(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>

    'calculateMerkleRoot(bytes32[],uint256,bytes32)'(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>

    executeTransaction(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)'(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    initialize(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'initialize(address,address)'(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    isMaster(overrides?: CallOverrides): Promise<[boolean]>

    'isMaster()'(overrides?: CallOverrides): Promise<[boolean]>

    l2ToL1Block(overrides?: CallOverrides): Promise<[BigNumber]>

    'l2ToL1Block()'(overrides?: CallOverrides): Promise<[BigNumber]>

    l2ToL1EthBlock(overrides?: CallOverrides): Promise<[BigNumber]>

    'l2ToL1EthBlock()'(overrides?: CallOverrides): Promise<[BigNumber]>

    l2ToL1Sender(overrides?: CallOverrides): Promise<[string]>

    'l2ToL1Sender()'(overrides?: CallOverrides): Promise<[string]>

    l2ToL1Timestamp(overrides?: CallOverrides): Promise<[BigNumber]>

    'l2ToL1Timestamp()'(overrides?: CallOverrides): Promise<[BigNumber]>

    outboxes(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    'outboxes(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>

    outboxesLength(overrides?: CallOverrides): Promise<[BigNumber]>

    'outboxesLength()'(overrides?: CallOverrides): Promise<[BigNumber]>

    processOutgoingMessages(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'processOutgoingMessages(bytes,uint256[])'(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>

    rollup(overrides?: CallOverrides): Promise<[string]>

    'rollup()'(overrides?: CallOverrides): Promise<[string]>
  }

  beacon(overrides?: CallOverrides): Promise<string>

  'beacon()'(overrides?: CallOverrides): Promise<string>

  bridge(overrides?: CallOverrides): Promise<string>

  'bridge()'(overrides?: CallOverrides): Promise<string>

  calculateItemHash(
    l2Sender: string,
    destAddr: string,
    l2Block: BigNumberish,
    l1Block: BigNumberish,
    l2Timestamp: BigNumberish,
    amount: BigNumberish,
    calldataForL1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>

  'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)'(
    l2Sender: string,
    destAddr: string,
    l2Block: BigNumberish,
    l1Block: BigNumberish,
    l2Timestamp: BigNumberish,
    amount: BigNumberish,
    calldataForL1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>

  calculateMerkleRoot(
    proof: BytesLike[],
    path: BigNumberish,
    item: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>

  'calculateMerkleRoot(bytes32[],uint256,bytes32)'(
    proof: BytesLike[],
    path: BigNumberish,
    item: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>

  executeTransaction(
    outboxIndex: BigNumberish,
    proof: BytesLike[],
    index: BigNumberish,
    l2Sender: string,
    destAddr: string,
    l2Block: BigNumberish,
    l1Block: BigNumberish,
    l2Timestamp: BigNumberish,
    amount: BigNumberish,
    calldataForL1: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)'(
    outboxIndex: BigNumberish,
    proof: BytesLike[],
    index: BigNumberish,
    l2Sender: string,
    destAddr: string,
    l2Block: BigNumberish,
    l1Block: BigNumberish,
    l2Timestamp: BigNumberish,
    amount: BigNumberish,
    calldataForL1: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  initialize(
    _rollup: string,
    _bridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'initialize(address,address)'(
    _rollup: string,
    _bridge: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  isMaster(overrides?: CallOverrides): Promise<boolean>

  'isMaster()'(overrides?: CallOverrides): Promise<boolean>

  l2ToL1Block(overrides?: CallOverrides): Promise<BigNumber>

  'l2ToL1Block()'(overrides?: CallOverrides): Promise<BigNumber>

  l2ToL1EthBlock(overrides?: CallOverrides): Promise<BigNumber>

  'l2ToL1EthBlock()'(overrides?: CallOverrides): Promise<BigNumber>

  l2ToL1Sender(overrides?: CallOverrides): Promise<string>

  'l2ToL1Sender()'(overrides?: CallOverrides): Promise<string>

  l2ToL1Timestamp(overrides?: CallOverrides): Promise<BigNumber>

  'l2ToL1Timestamp()'(overrides?: CallOverrides): Promise<BigNumber>

  outboxes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

  'outboxes(uint256)'(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>

  outboxesLength(overrides?: CallOverrides): Promise<BigNumber>

  'outboxesLength()'(overrides?: CallOverrides): Promise<BigNumber>

  processOutgoingMessages(
    sendsData: BytesLike,
    sendLengths: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'processOutgoingMessages(bytes,uint256[])'(
    sendsData: BytesLike,
    sendLengths: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>

  rollup(overrides?: CallOverrides): Promise<string>

  'rollup()'(overrides?: CallOverrides): Promise<string>

  callStatic: {
    beacon(overrides?: CallOverrides): Promise<string>

    'beacon()'(overrides?: CallOverrides): Promise<string>

    bridge(overrides?: CallOverrides): Promise<string>

    'bridge()'(overrides?: CallOverrides): Promise<string>

    calculateItemHash(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>

    'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)'(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>

    calculateMerkleRoot(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>

    'calculateMerkleRoot(bytes32[],uint256,bytes32)'(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>

    executeTransaction(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>

    'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)'(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>

    initialize(
      _rollup: string,
      _bridge: string,
      overrides?: CallOverrides
    ): Promise<void>

    'initialize(address,address)'(
      _rollup: string,
      _bridge: string,
      overrides?: CallOverrides
    ): Promise<void>

    isMaster(overrides?: CallOverrides): Promise<boolean>

    'isMaster()'(overrides?: CallOverrides): Promise<boolean>

    l2ToL1Block(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1Block()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1EthBlock(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1EthBlock()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1Sender(overrides?: CallOverrides): Promise<string>

    'l2ToL1Sender()'(overrides?: CallOverrides): Promise<string>

    l2ToL1Timestamp(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1Timestamp()'(overrides?: CallOverrides): Promise<BigNumber>

    outboxes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

    'outboxes(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>

    outboxesLength(overrides?: CallOverrides): Promise<BigNumber>

    'outboxesLength()'(overrides?: CallOverrides): Promise<BigNumber>

    processOutgoingMessages(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>

    'processOutgoingMessages(bytes,uint256[])'(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>

    rollup(overrides?: CallOverrides): Promise<string>

    'rollup()'(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    OutBoxTransactionExecuted(
      destAddr: string | null,
      l2Sender: string | null,
      outboxIndex: BigNumberish | null,
      transactionIndex: null
    ): EventFilter

    OutboxEntryCreated(
      batchNum: BigNumberish | null,
      outboxIndex: null,
      outputRoot: null,
      numInBatch: null
    ): EventFilter
  }

  estimateGas: {
    beacon(overrides?: CallOverrides): Promise<BigNumber>

    'beacon()'(overrides?: CallOverrides): Promise<BigNumber>

    bridge(overrides?: CallOverrides): Promise<BigNumber>

    'bridge()'(overrides?: CallOverrides): Promise<BigNumber>

    calculateItemHash(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)'(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateMerkleRoot(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'calculateMerkleRoot(bytes32[],uint256,bytes32)'(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    executeTransaction(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>

    'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)'(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>

    initialize(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'initialize(address,address)'(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    isMaster(overrides?: CallOverrides): Promise<BigNumber>

    'isMaster()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1Block(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1Block()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1EthBlock(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1EthBlock()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1Sender(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1Sender()'(overrides?: CallOverrides): Promise<BigNumber>

    l2ToL1Timestamp(overrides?: CallOverrides): Promise<BigNumber>

    'l2ToL1Timestamp()'(overrides?: CallOverrides): Promise<BigNumber>

    outboxes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'outboxes(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    outboxesLength(overrides?: CallOverrides): Promise<BigNumber>

    'outboxesLength()'(overrides?: CallOverrides): Promise<BigNumber>

    processOutgoingMessages(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>

    'processOutgoingMessages(bytes,uint256[])'(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>

    rollup(overrides?: CallOverrides): Promise<BigNumber>

    'rollup()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    beacon(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'beacon()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'bridge()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    calculateItemHash(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'calculateItemHash(address,address,uint256,uint256,uint256,uint256,bytes)'(
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    calculateMerkleRoot(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'calculateMerkleRoot(bytes32[],uint256,bytes32)'(
      proof: BytesLike[],
      path: BigNumberish,
      item: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    executeTransaction(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'executeTransaction(uint256,bytes32[],uint256,address,address,uint256,uint256,uint256,uint256,bytes)'(
      outboxIndex: BigNumberish,
      proof: BytesLike[],
      index: BigNumberish,
      l2Sender: string,
      destAddr: string,
      l2Block: BigNumberish,
      l1Block: BigNumberish,
      l2Timestamp: BigNumberish,
      amount: BigNumberish,
      calldataForL1: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    initialize(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'initialize(address,address)'(
      _rollup: string,
      _bridge: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    isMaster(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'isMaster()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2ToL1Block(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2ToL1Block()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2ToL1EthBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2ToL1EthBlock()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2ToL1Sender(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2ToL1Sender()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    l2ToL1Timestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'l2ToL1Timestamp()'(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    outboxes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'outboxes(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    outboxesLength(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'outboxesLength()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    processOutgoingMessages(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'processOutgoingMessages(bytes,uint256[])'(
      sendsData: BytesLike,
      sendLengths: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    rollup(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'rollup()'(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
